# Learn Posture

use machine learning to recognize robot's posture (following the example in [scikit-learn-intro.ipynb](./scikit-learn-intro.ipynb) )

## 1. Data collection

We have colleceted data before, you need to add new data if you want to add new posture.

* the dateset are in *robot_pose_data* folder
* each file contains the data belongs to this posture, e.g. the data in *Back* file are collected when robot was in "Back" posture
* the data file can be load by ```pickle```, e.g. ```pickle.load(open('Back'))```, the data is a list of feature data
* the features (e.g. each row of the data) are ['LHipYawPitch', 'LHipRoll', 'LHipPitch', 'LKneePitch', 'RHipYawPitch', 'RHipRoll', 'RHipPitch', 'RKneePitch', 'AngleX', 'AngleY'], where 'AngleX' and 'AngleY' are body angle (e.g. ```Perception.imu```) and others are joint angles.

## 2. Data preprocessing

In [3]:
%pylab inline
import pickle
from os import listdir, path
import numpy as np
from sklearn import svm, metrics

ROBOT_POSE_DATA_DIR = 'robot_pose_data'

Populating the interactive namespace from numpy and matplotlib


In [5]:
classes = listdir(ROBOT_POSE_DATA_DIR)
print(classes)

['Knee', 'Stand', 'HeadBack', 'Frog', 'Crouch', 'Sit', 'Left', 'Back', 'Right', 'StandInit', 'Belly']


In [17]:
def load_pose_data(i):
    '''load pose data from file'''
    data = []
    target = []
    
    filename = path.join(ROBOT_POSE_DATA_DIR, classes[i])
    data = np.array(pickle.load(open(filename, "br")))
    target = np.full(len(data), i)

    return data, target

x, y = load_pose_data(3)
np.array(x).shape

(10, 10)

In [20]:
# load all the data
all_data = []
all_target = []
# YOUR CODE HERE

for c in range(len(classes)):
    data, target = load_pose_data(c)
    all_data.append(data)
    all_target.append(target)
    
all_data = np.concatenate(all_data)
all_target = np.concatenate(all_target)

print('total number of data', len(all_data))

total number of data 222


In [22]:
# shuffule data
permutation = np.random.permutation(len(all_data))
n_training_data = int(len(all_data) * 0.7)
training_data = permutation[:n_training_data]
test_data = permutation[n_training_data:]

## 3. Learn on training data

In scikit-learn, an estimator for classification is a Python object that implements the methods fit(X, y) and predict(T). An example of an estimator is the class sklearn.svm.SVC that implements support vector classification.

In [23]:
clf = svm.SVC(gamma=0.001, C=100.)

### learning

In [24]:
# YOUR CODE HERE
clf.fit(all_data[training_data], all_target[training_data])

SVC(C=100.0, gamma=0.001)

### predicting

In [31]:
clf.predict(all_data[test_data]), all_target[test_data]

(array([ 5,  7,  7,  5,  7,  9, 10,  4,  9,  5,  9,  4,  8,  5,  3,  9,  6,
         4,  4,  9,  5,  9,  4,  9,  9,  8, 10,  7,  7,  0,  9, 10,  5,  8,
         6,  9,  1,  7,  9,  3,  3,  2, 10,  2, 10,  6,  5, 10, 10,  4,  6,
         1,  9, 10,  7,  7,  5,  6,  5,  4,  8,  6,  9,  9,  9,  7,  4]),
 array([ 5,  7,  7,  5,  7,  9, 10,  4,  9,  5,  9,  4,  8,  5,  3,  9,  6,
         4,  4,  9,  5,  9,  4,  9,  9,  8, 10,  7,  7,  0,  9, 10,  5,  8,
         6,  9,  1,  7,  9,  3,  3,  2, 10,  2, 10,  6,  5, 10, 10,  4,  6,
         1,  9, 10,  7,  7,  5,  6,  5,  4,  8,  6,  9,  9,  9,  7,  4]))

In [32]:
def evaluate(expected, predicted):
    print("Classification report:\n%s\n" % metrics.classification_report(expected, predicted))

    print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))

In [34]:
expected = []
predicted = []
# YOUR CODE HERE
predicted, expected = clf.predict(all_data[training_data]), all_target[training_data]

evaluate(expected, predicted)

Classification report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00         8
           3       1.00      1.00      1.00         7
           4       0.96      1.00      0.98        22
           5       1.00      1.00      1.00        17
           6       1.00      1.00      1.00        14
           7       1.00      1.00      1.00        14
           8       1.00      0.86      0.92         7
           9       1.00      1.00      1.00        37
          10       1.00      1.00      1.00        11

    accuracy                           0.99       155
   macro avg       1.00      0.99      0.99       155
weighted avg       0.99      0.99      0.99       155


Confusion matrix:
[[ 9  0  0  0  0  0  0  0  0  0  0]
 [ 0  9  0  0  0  0  0  0  0  0  0]
 [ 0  0  8  0  0  0  0  0  0  0  0]
 [ 0  0  0  7  0  0  0  0  0  0  0]
 

## 4. Evaluate on the test data

In [35]:
expected = []
predicted = []
# YOUR CODE HERE
predicted, expected = clf.predict(all_data[test_data]), all_target[test_data]

evaluate(expected, predicted)

Classification report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         2
           2       1.00      1.00      1.00         2
           3       1.00      1.00      1.00         3
           4       1.00      1.00      1.00         8
           5       1.00      1.00      1.00         9
           6       1.00      1.00      1.00         6
           7       1.00      1.00      1.00         9
           8       1.00      1.00      1.00         4
           9       1.00      1.00      1.00        15
          10       1.00      1.00      1.00         8

    accuracy                           1.00        67
   macro avg       1.00      1.00      1.00        67
weighted avg       1.00      1.00      1.00        67


Confusion matrix:
[[ 1  0  0  0  0  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  0  0  0  0  0]
 [ 0  0  2  0  0  0  0  0  0  0  0]
 [ 0  0  0  3  0  0  0  0  0  0  0]
 

## 5. Deploy to the real system

We can simple use `pickle` module to serialize the trained classifier.

In [37]:
import pickle
ROBOT_POSE_CLF = 'robot_pose.pkl'
pickle.dump(clf, open(ROBOT_POSE_CLF, 'wb'))

Then, in the application we can load the trained classifier again.

In [39]:
clf2 = pickle.load(open(ROBOT_POSE_CLF, "rb"))
clf2.predict([all_data[-1]]), all_target[-1]

(array([10]), 10)